# Zsh initialization and core settings

# History configuration
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt SHARE_HISTORY        # Share history between sessions
setopt HIST_IGNORE_SPACE    # Don't record commands starting with space
setopt HIST_IGNORE_DUPS     # Don't record duplicated commands

# Helpers for caching expensive startup initialization (needed before compinit).
source "$SETUP_DIR/zsh/cache.zsh"

# Completion script cache directory; add it to fpath before compinit.
fpath=("$ZSH_CACHE_DIR/completions" $fpath)

# grok completion uses #compdef and the correct filename (_grok), so adding it
# to fpath lets compinit load it lazily. (N) silently omits nonexistent matches.
fpath=("$HOME/.grok/completions/zsh"(N) $fpath)

# uv completion is 520 KB and takes 70ms to eval. Its #compdef format lets
# compinit load it lazily from fpath, avoiding startup cost.
_zcomp_before=("$ZSH_CACHE_DIR"/completions/*(N.))
_zsh_cache_completion _uv  "${commands[uv]}"  -- uv generate-shell-completion zsh
_zsh_cache_completion _uvx "${commands[uvx]}" -- uvx --generate-shell-completion zsh
# The _restish.zsh shipped by restish is generated by cobra and ends with
# an `if [ "$funcstack[1]" = "_restish" ]` guard. Unless the filename is `_restish`,
# the guard fails during lazy loading, so generate it in the cache instead of adding its directory to fpath.
# (Sourcing adds 6.6ms to startup; the generated file has the right name and loads lazily at no startup cost.)
_zsh_cache_completion _restish "${commands[restish]}" -- restish completion zsh
_zcomp_after=("$ZSH_CACHE_DIR"/completions/*(N.))

# Completion system
# Full compinit takes 240ms versus 10ms with -C. However, -C reuses the dump as-is
# and misses new completions on fpath. Rebuild fully only if the dump is missing,
# older than 24 hours, or a new completion file has been added.
# (Lazy loading picks up updates, so -C is fine for them; only new registrations need detection.
# Without this check, _uv may remain unrecognized for up to 24 hours after installing this configuration.)
autoload -Uz compinit
# Use plain glob qualifiers ((#q...) requires EXTENDED_GLOB).
# N=empty if absent / .=regular file / mh-24=modified within 24 hours.
_zcompdump_fresh=("${ZDOTDIR:-$HOME}"/.zcompdump(N.mh-24))
if (( $#_zcompdump_fresh )) && (( $#_zcomp_after == $#_zcomp_before )); then
    compinit -C
else
    compinit
fi
unset _zcompdump_fresh _zcomp_before _zcomp_after

# Enable colors
autoload -Uz colors
colors

# Load zsh configurations
# Order matters: env.zsh must be first to set up environment
source "$SETUP_DIR/zsh/env.zsh"
source "$SETUP_DIR/zsh/completion.zsh"
source "$SETUP_DIR/zsh/gwt.zsh"
source "$SETUP_DIR/zsh/ghu.zsh"
source "$SETUP_DIR/zsh/gh.zsh"
source "$SETUP_DIR/zsh/github.zsh"
source "$SETUP_DIR/zsh/gcloud.zsh"
source "$SETUP_DIR/zsh/anyenv.zsh"
source "$SETUP_DIR/zsh/goenv.zsh"
source "$SETUP_DIR/zsh/prompt-line.zsh"
source "$SETUP_DIR/zsh/ai.zsh"
source "$SETUP_DIR/zsh/aliases.zsh"
source "$SETUP_DIR/zsh/functions.zsh"
source "$SETUP_DIR/zsh/keybindings.zsh"
source "$SETUP_DIR/zsh/iterm2.zsh"
# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh" # Official iTerm integration

# Display cwd in the cmux sidebar (inside cmux only).
if [[ -n "$CMUX_SHELL_INTEGRATION" ]]; then
    source "$HOME/.config/cmux/sidebar-cwd.zsh"
fi

# Initialize tools
# Do not run rehash at shell startup (--no-rehash), because:
#   1. Rehashing five environments adds about one second to startup.
#   2. Closing the terminal during rehash leaves the lock (.pyenv-shim),
#      blocking every subsequent shell startup for 60 seconds and emitting
#      "pyenv: cannot rehash: couldn't acquire lock".
# After installing new executables (pip install / gem install / npm i -g, etc.),
# run `pyenv rehash` or the corresponding command explicitly.
#
# anyenv init itself also takes 550ms because it starts a process per environment. Its output
# is stable until environments or versions change, so cache and source it.
# (See zsh/anyenv.zsh for generation details.) Run `zsh-cache-clear` if content seems stale.
_zsh_cache_source anyenv-init.zsh \
    "$HOME/.anyenv/envs" "$HOME/.anyenv/envs"/*/libexec(N) "${commands[anyenv]}" \
    "$HOMEBREW_PREFIX/Cellar/anyenv"(N) \
    -- _zsh_gen_anyenv_init \
    || eval "$(anyenv init - --no-rehash)"

# --no-rehash also omits goenv's GOROOT/GOPATH setup, so restore that explicitly.
# Upstream `goenv rehash --only-manage-paths` takes 190ms; use _goenv_set_paths
# (zsh/goenv.zsh) to resolve the same values without subprocesses.
_goenv_set_paths

eval "$(zoxide init zsh)"

# Call the greeting function when starting an interactive shell
if [[ $- == *i* ]]; then
#    display_greeting
    auto_make_login
fi

# Source local configurations if they exist
if [[ -f ~/.zshrc.local ]]; then
    source ~/.zshrc.local
fi

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# security
# See: https://github.com/AikidoSec/safe-chain
source ~/.safe-chain/scripts/init-posix.sh # Safe-chain Zsh initialization script
# socket.dev
# See: https://docs.socket.dev/docs/safe-npm-faq
#alias npm="socket-npm"
#alias npx="socket-npx"
#compdef \_npm socket-npm

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
case ":$PATH:" in
*":$PNPM_HOME/bin:"*) ;;
*) export PATH="$PNPM_HOME/bin:$PATH" ;;
esac
# pnpm end

# Visivo
export PATH="$HOME/.visivo/bin:$PATH"


# PromptLine (zsh/prompt-line.zsh refreshes stale caches in the background).
_prompt_line_start_refresh


# Check zshexit behavior.
zshexit() {
    echo "[zshexit] shell PID=$$ exiting at $(date '+%H:%M:%S')"
}

iterm-run() {
  osascript -e "
  tell application \"iTerm2\"
    create window with default profile
    tell current session of current window
      delay 0.1
      write text \"$*\"
    end tell
  end tell"
}

# obsidian
export OBSIDIAN_VAULT="$HOME/vault"